FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy application files
COPY ./frontend .

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "start"]
